In [108]:
import numpy as np
import pandas as pd

In [109]:
class scratch_LR:

    def __init__(self):
        self.m = None
        self.b = None

    def fit(self,X_train, y_train):
        mean_x = X_train.mean()
        mean_y = y_train.mean()
        num,den=0,0
        for i in range(len(X_train)):
            num+= (X_train[i]-mean_x)*(y_train[i]-mean_y)
            den+= (X_train[i]-mean_x)**2
        self.m = num/den
        self.b = mean_y - self.m*mean_x
            
            
    def predict(self,X_test):
        return self.m*X_test + self.b

    def mean_absolute_error(self,X_test,y_test):
        error = 0
        for i in range(len(X_test)):
            error+= (abs(lr.predict(X_test[i])-y_test[i]))
        error/=len(X_test)
        return error * 100
        

In [110]:
df = pd.read_csv('placement.csv')

In [111]:
df.head()

,cgpa,package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57


In [112]:
X = df.iloc[:,0].values
y = df.iloc[:,1].values

In [113]:
lr = scratch_LR()

In [114]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [115]:
lr.fit(X_train,y_train)

In [116]:
len(X_train)

160

In [117]:
X_train

array([7.76, 6.33, 8.11, 7.73, 5.84, 7.48, 5.84, 7.43, 6.31, 6.06, 7.69,
       5.1 , 7.39, 6.47, 6.35, 7.14, 8.22, 6.13, 6.22, 7.91, 9.04, 6.51,
       6.59, 5.95, 5.38, 7.89, 6.78, 6.66, 8.63, 5.11, 6.86, 4.26, 7.28,
       5.95, 8.6 , 6.94, 8.94, 7.12, 6.79, 5.23, 7.08, 7.11, 6.1 , 5.12,
       7.28, 6.93, 5.58, 5.84, 6.26, 7.87, 6.61, 5.99, 7.3 , 7.84, 7.94,
       7.05, 6.93, 7.21, 7.57, 6.75, 6.97, 6.85, 6.22, 7.37, 7.82, 5.79,
       4.79, 6.3 , 6.73, 8.58, 6.89, 6.98, 8.99, 7.6 , 8.2 , 8.13, 4.73,
       6.68, 6.07, 6.34, 6.85, 7.9 , 5.66, 7.13, 4.85, 8.09, 6.19, 5.84,
       9.06, 5.32, 6.96, 8.44, 5.88, 7.95, 7.33, 6.19, 5.91, 8.31, 6.22,
       7.62, 6.12, 6.1 , 5.42, 7.35, 7.36, 7.25, 6.89, 8.93, 7.77, 7.63,
       8.37, 8.31, 6.94, 7.66, 6.53, 7.42, 9.31, 8.87, 8.28, 6.37, 6.19,
       7.36, 6.5 , 8.35, 7.04, 6.09, 5.61, 7.93, 5.12, 6.6 , 6.14, 5.48,
       9.16, 6.75, 5.89, 6.76, 7.61, 7.11, 7.56, 9.58, 6.93, 6.47, 7.38,
       7.19, 6.07, 6.71, 7.28, 8.15, 7.28, 7.2 , 7.

In [118]:
lr.predict(X_test)

array([2.9383335 , 4.36894346, 3.18258398, 1.89736121, 3.49662031,
       3.35123312, 2.76968435, 2.94996447, 3.07208971, 3.94441286,
       3.57222165, 2.94996447, 2.75805338, 2.64755911, 3.67108494,
       3.2174769 , 3.97930579, 2.90925606, 2.19395108, 3.31052471,
       4.29915761, 2.8918096 , 1.87409926, 2.30444534, 3.62456104,
       2.12998071, 3.9269664 , 2.36841571, 1.5716939 , 2.06601035,
       2.31026083, 3.6885314 , 3.5024358 , 3.03719679, 2.57195777,
       2.39167766, 3.170953  , 3.82228762, 3.15932203, 2.94414898])

In [119]:
y_test

array([3.09, 4.02, 3.42, 1.37, 3.14, 3.96, 2.79, 3.57, 3.49, 3.52, 3.76,
       2.98, 2.6 , 2.72, 3.76, 2.88, 4.08, 2.87, 2.1 , 3.31, 3.79, 2.35,
       1.86, 2.42, 3.89, 2.55, 4.36, 2.24, 1.94, 2.16, 3.26, 4.08, 3.67,
       3.64, 3.23, 2.84, 2.99, 4.03, 2.94, 2.51])

In [120]:
lr.mean_absolute_error(X_test,y_test)

np.float64(29.931188593316804)